avoids deserializing values in getAllKeysIter
we delete old records from wallet datastores in batches in
'cleanupDeletedAccounts' to avoid blocking the node during lengthy delete
operations.

however, we use 'getAllKeysIter' to iterate over keys and delete them one by
one. 'getAllKeysIter' calls 'getAllIter' which iterates over keys and values.
during this iteration 'getAllIter' decodes the key and deserializes the value.
this deserialization is problematic if the value encoding has changed.

for example, the latest network reset changed asset generation. the database
        fails to deserialize old transaction data because the asset identifiers
        in the old transactions are now invalid:

```
Error: InvalidAssetIdentifier
    at <anonymous> (/Users/hughy/Code/ironfish/ironfish/src/primitives/transaction.ts:95:27)
    at Function.from (<anonymous>)
    at Transaction (/Users/hughy/Code/ironfish/ironfish/src/primitives/transaction.ts:91:24)
    at TransactionValueEncoding.deserialize (/Users/hughy/Code/ironfish/ironfish/src/wallet/walletdb/transactionValue.ts:58:25
```

we can solve this problem by preventing 'getAllKeysIter' from deserializing
values unnecessarily.

- implements '_getAllIter' to iterate over database entries without decoding
  keys and deserializing values
- use '_getAllIter' in 'getAllKeysIter' and decode keys before yielding

'_getAllIter' currently has to handle both serialized and deserialized values
because a transaction cache contains values that have already been deserialized.
in the future we might revisit the transaction cache and change it to only store
encoded keys and serialized values to match the database.