clears old wallet data without deserialization
we delete old records from wallet datastores in batches in
'cleanupDeletedAccounts' to avoid blocking the node during lengthy delete
operations.

however, we use 'getAllKeysIter' to iterate over keys and delete them one by
one. 'getAllKeysIter' calls 'getAllIter' which iterates over keys _and_ values.
during this iteration 'getAllIter' decodes the key and deserializes the value.
this deserialization is problematic if the value encoding has changed.

for example, the latest network reset changed asset generation. the database
fails to deserialize old transaction data because the asset identifiers in the
old transactions are now invalid:

```
Error: InvalidAssetIdentifier
    at <anonymous> (/Users/hughy/Code/ironfish/ironfish/src/primitives/transaction.ts:95:27)
    at Function.from (<anonymous>)
    at Transaction (/Users/hughy/Code/ironfish/ironfish/src/primitives/transaction.ts:91:24)
    at TransactionValueEncoding.deserialize (/Users/hughy/Code/ironfish/ironfish/src/wallet/walletdb/transactionValue.ts:58:25)
```

we can solve this problem by using the levelup 'clear' method
(https://github.com/Level/levelup#dbclearoptions-callback) to delete entries in
a key range instead of deleting keys one by one. using 'clear' does not
deserialize values.

'clear' also accepts a 'limit' option so that we can still perform deletions on
batches of records.

- modifies levelup definition of clear to accept 'DatabaseIteratorOptions' and
  pass those options to the database
- uses clear with limit in walletdb cleanupDeletedAccounts instead of iterating
  over keys and deleting each key